environment:
    global:
        # Your package name
        PACKAGE: "AmdButler"
        SUBLIME_TEXT_VERSION : "3"

install:
    - ps: start-filedownload "https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/appveyor.ps1"
    - ps: .\appveyor.ps1 "bootstrap" -verbose

build: off

test_script:
    - ps: .\appveyor.ps1 "run_tests" -verbose